---
name: Ubuntu 20.04

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  pull_request:
    branches: []

concurrency:
  group: dns

jobs:
  ansible-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3
      - name: Test Galaxy role
        env:
          CF_Token: ${{ secrets.CF_Token }}
          CF_Account_ID: ${{ secrets.CF_Account_ID }}
          CF_Zone_ID: ${{ secrets.CF_Zone_ID }}
        run: >
            CONT_ID=$(podman run --rm -v ${{ github.workspace }}:/repo -v /sys/fs/cgroup:/sys/fs/cgroup:ro
            --tmpfs /tmp --tmpfs /run --privileged --detach bviktor/ansible-systemd-ubuntu:20.04) &&
            podman exec --env-file tests/env.list ${CONT_ID} /bin/bash -c
            "if [ -f requirements.yml ]; then ansible-galaxy role install --force -r requirements.yml -p ..; fi &&
            ANSIBLE_ROLES_PATH=.. ANSIBLE_FORCE_COLOR=true ansible-playbook tests/main.yml" &&
            podman stop ${CONT_ID}
